export const environment = {
  production: true,
  clientName: 'renova',
  apiUrl: 'http://localhost:5102/api/renovae/v1',
  logoUrl: '/renova/logo.webp',
  faviconUrl: '/renova/favicon.ico',
  appTitle: 'RENOVAE',
  auth: {
    tokenStorage: 'cookie' as const,
    refreshTokenCookie: 'apolo_rt',
    accessTokenKey: 'auth_token',
  },
  features: {
    comparator: true,
    sips: true,
    statistics: true,
    history: true,
    commissions: true,
    usersManagement: true,
    forgotPassword: true,
    resetPassword: true,
    quickAction: true,
    excelReports: true,
    contracts: false,
    userDetail: false,
    support: false,
  },
};
