export const environment = {
  production: true,
  clientName: 'apolo',
  apiUrl: 'https://api.apoloenergies.es/test/api/apolo/v1',
  logoUrl: '/apolo/apolologo.webp',
  faviconUrl: '/apolo/favicon.ico',
  appTitle: 'APOLO ENERGIES',
  contractsUrl: null as string | null,
  supportUrl:   null as string | null,
  auth: {
    tokenStorage: 'cookie' as const,
    refreshTokenCookie: 'apolo_rt',
    accessTokenKey: 'auth_token',
  },
  features: {
    comparator: true,
    sips: true,
    statistics: true,
    history: true,
    commissions: true,
    usersManagement: true,
    forgotPassword: true,
    resetPassword: true,
    quickAction: true,
    excelReports: true,
    contracts: true,
    userDetail: true,
    opportunities: true,
    markets: true,
    support: false,
  },
};
