export const environment = {
  production: true,
  clientName: 'coexpal',
  apiUrl: 'https://api.apoloenergies.es',
  logoUrl: '/coexpal/logo.svg',
  features: {
    comparator: true,
    sips: true,
    statistics: true,
    history: true,
    commissions: true,
    usersManagement: true,
    forgotPassword: true,
    resetPassword: true,
    quickAction: true,
    excelReports: true,
    contracts: false,
    support: false,
  },
};