export interface ServicioListItem {
  Id:                           number;
  IdDelegacion:                 number;
  IdComercial:                  number;
  IdCliente:                    number;
  IdSuministro:                 number;
  CUPS:                         string;
  NombreSuministro:             string;
  Tarifa:                       string;
  NombreOfertaCTF:              string;
  TipoPrecioOfertaCTF:          string;
  NombreCliente:                string;
  RazonSocialCliente:           string;
  NIFCliente:                   string;
  RazonSocialTitularSuministro: string;
  NIFTitularSuministro:         string;
  EmailFacturacion:             string;
  Estado:                       string;
  FechaInicio:                  string | null;
  FechaFin:                     string | null;
  FechaEstado:                  string | null;
  NombreComercial:              string;
  NombreDelegacion:             string;
  DireccionSuministro:          string;
  ProvinciaSuministro:          string;
  PoblacionSuministro:          string;
  CPSuministro:                 string;
  TipoPagoFacturas:             string;
  CodigoCuentaDomiciliacion:    string;
  ImporteBaseComisiones:        number;
  Renovacion:                   boolean;
  ConsumoAnualContrato:         number;
  ConsumoAnualSuministro:       number;
  ConsumoAnualP1:               number;
  ConsumoAnualP2:               number;
  ConsumoAnualP3:               number;
  ConsumoAnualP4:               number;
  ConsumoAnualP5:               number;
  ConsumoAnualP6:               number;
  PotenciaP1:                   number | null;
  PotenciaP2:                   number | null;
  PotenciaP3:                   number | null;
  PotenciaP4:                   number | null;
  PotenciaP5:                   number | null;
  PotenciaP6:                   number | null;
  PrecioPotenciaP1:             number;
  PrecioPotenciaP2:             number;
  PrecioPotenciaP3:             number;
  PrecioPotenciaP4:             number;
  PrecioPotenciaP5:             number;
  PrecioPotenciaP6:             number;
  PrecioEnergiaP1:              number;
  PrecioEnergiaP2:              number;
  PrecioEnergiaP3:              number;
  PrecioEnergiaP4:              number;
  PrecioEnergiaP5:              number;
  PrecioEnergiaP6:              number;
}
